//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5466
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace SuperDeviceFactory.AlarmStarHelper
{

    /// <summary>
    /// 报警信息
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class AlarmEventMsg
    {

        private string alarmEventVersionField;

        private string alarmIDField;

        private string deviceIDField;

        private string loaclIPField;

        private string feedNumberField;

        private string feedNicknameField;

        private string frameIDField;

        private string alarmTypeField;

        private string alarmTimeField;

        private string alarmBitmapField;

        private string trackUpLeftField;

        private string trackDownRightField;

        private string alarmActionField;

        private string alarmFilePathField;



       /// <summary>
       /// 版本信息
       /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AlarmEventVersion
        {
            get
            {
                return this.alarmEventVersionField;
            }
            set
            {
                this.alarmEventVersionField = value;
            }
        }

        /// <summary>
        /// 报警标识
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AlarmID
        {
            get
            {
                return this.alarmIDField;
            }
            set
            {
                this.alarmIDField = value;
            }
        }

        /// <summary>
        /// BW设备标识
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DeviceID
        {
            get
            {
                return this.deviceIDField;
            }
            set
            {
                this.deviceIDField = value;
            }
        }

        /// <summary>
        /// 设备本地ip
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LoaclIP
        {
            get
            {
                return this.loaclIPField;
            }
            set
            {
                this.loaclIPField = value;
            }
        }

        /// <summary>
        /// 分析通道号
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FeedNumber
        {
            get
            {
                return this.feedNumberField;
            }
            set
            {
                this.feedNumberField = value;
            }
        }


        /// <summary>
        /// 通道标识（硬盘录像机IP以及通道号）
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FeedNickname
        {
            get
            {
                return this.feedNicknameField;
            }
            set
            {
                this.feedNicknameField = value;
            }
        }

        /// <summary>
        /// 帧序号；指明轨迹对应的帧序号；与“媒体数据回调通知结构体”定义的帧序号一致。
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FrameID
        {
            get
            {
                return this.frameIDField;
            }
            set
            {
                this.frameIDField = value;
            }
        }



        /// <summary>
        /// 报警类型
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AlarmType
        {
            get
            {
                return this.alarmTypeField;
            }
            set
            {
                this.alarmTypeField = value;
            }
        }

        /// <summary>
        /// 报警发生时间；24小时制式，格式为：“YYYY-MM-DD HH:MM:SS
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AlarmTime
        {
            get
            {
                return this.alarmTimeField;
            }
            set
            {
                this.alarmTimeField = value;
            }
        }
        /// <summary>
        /// 报警目标左上角坐标（XX,XX）可选节点
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TrackUpLeft
        {
            get
            {
                return this.trackUpLeftField;
            }
            set
            {
                this.trackUpLeftField = value;
            }
        }

        /// <summary>
        /// 报警目标右下角坐标（XX,XX）可选节点
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TrackDownRight
        {
            get
            {
                return this.trackDownRightField;
            }
            set
            {
                this.trackDownRightField = value;
            }
        }
        /// <summary>
        /// 报警截图base64编码
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AlarmBitmap
        {
            get
            {
                return this.alarmBitmapField;
            }
            set
            {
                this.alarmBitmapField = value;
            }
        }

        /// <summary>
        /// 报警动作类型；0：报警开始1：报警结束。
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AlarmAction
        {
            get
            {
                return this.alarmActionField;
            }
            set
            {
                this.alarmActionField = value;
            }
        }

        /// <summary>
        /// 报警录像文件地址
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AlarmFilePath
        {
            get
            {
                return this.alarmFilePathField;
            }
            set
            {
                this.alarmFilePathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NewDataSet
    {

        private AlarmEventMsg[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AlarmEventMsg")]
        public AlarmEventMsg[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
}
